name: Run tests

on:
  push:

permissions:
  contents: read

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade flit pip
    - name: Build wheel
      run: |
        flit build --format wheel
    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/*.whl

  test:
    needs: [build-wheel]
    strategy:
      fail-fast: false
      matrix:
        version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12.0-beta.4"]

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '${{ matrix.version }}'
    - name: Download wheel
      uses: actions/download-artifact@v3
      with:
        name: wheel
        path: ./
    - name: Install wheel
      run: |
        pip install *.whl
    - name: Run tests without optional dependencies
      run: |
        python tests/test_all.py
    - name: Install optional dependencies
      run: |
        python -m pip install . '.[test]'
    - name: Run tests with optional dependencies
      run: |
        python tests/test_all.py
